
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from '../types';

export const generateImage = async (prompt: string, aspectRatio: AspectRatio): Promise<string> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable not set. Please configure it to use AI generation.");
    }
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the AI model.");
        }
    } catch (e) {
        console.error("Gemini API error:", e);
        const errorMessage = e instanceof Error ? e.message : "An unknown error occurred.";
        throw new Error(`Failed to generate image: ${errorMessage}`);
    }
};
